### ISSUE TITLE
SkipListDataPage>>#hasItems uses isRemoved but should use restoreValue

### ISSUE THREAD

**Issue by noha** [ApptiveGrid/Soil#361]

**Comment by MarcusDenker** [comment]
The problem is that at the level of the page, we have no access to the transaction, so we can not access restored values.

I think we need to first get the level clear. For example, we have SoilIndexIterator>>#nextAssociation #isEmpty taking removed values in account related to it's use of isEmpty, but not in general. For that we have #nextPresentAssociation.

As a first step, I think we need to have the pages just not caring about #isRemoved at all and move it all to the IndexedDictionary

**Comment by MarcusDenker** [comment]
See https://github.com/ApptiveGrid/Soil/pull/518 for the refactoring
